notifiers:
  - name: notification-channel-1
    type: slack
    uid: notifier1
    org_id: 1
    org_name: Main Org.
    is_default: true
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    settings:
      recipient: "channel"
      iconEmoji: ":alien:"
      token: "token"
      uploadImage: true
      url: "webhook"